version: '3.8'

services:
  db:
    image: mongo:6.0  
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: admin123  
      MONGO_INITDB_DATABASE: strava_mongoDB        
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db  
    networks:
      - mongo-network

volumes:
  mongo_data:  

networks:
  mongo-network:  

